//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Side_Steel_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class MInventory
    {
        public int id { get; set; }
        public string Item_Name { get; set; }
        public Nullable<int> Quatity { get; set; }
        public string Quality { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> Total { get; set; }
        public string Providerr { get; set; }
        public string Availabe { get; set; }
        public string Item_location { get; set; }
    }
}
